---

- name: ensure artifact directory exists
  become: true
  file:
    path: ./artifact
    state: directory

- name: "extract archived artifact"
  become: true
  unarchive:
    src: ~/project/./circleci/artifact.tar.gz
    dest: ./artifact

- name: "random"
  become: true
  shell: |
    touch test.txt

- name: "start app"
  become: true
  shell: |
    cd ./artifact
    npm install 
    pm2 stop default 
    pm2 start npm -- start