---
- name: ensure artifact directory exists
  file:
    path: ~/artifact
    state: directory

- name: "extract archived artifact"
  become: true
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/artifact

- name: "start app"
  shell: |
    cd ~/artifact
    npm install 
    pm2 stop default 
    pm2 start npm -- start