---

- name: ensure artifact directory exists
  become: true
  file:
    path: ./artifact
    state: directory

# - name: "extract archived artifact"
#   become: true
#   unarchive:
#     src: files/artifact.tar.gz
#     dest: ./artifact

- name: "Move backend files to web server"
  become: true
  copy:
      src: /root/project/artifact.tar.gz
      dest: "./artifact"
      owner: ubuntu
      mode: 0777

- name: "Unzip backend files"
  become: true
  shell: |
    cd ./artifact
    tar xvzf ./artifact/artifact.tar.gz
    rm -rf ./artifact.tar.gz

# - name: "start app"
#   become: true
#   shell: |
#     cd ./artifact
#     npm install 
#     pm2 stop default 
#     pm2 start npm -- start